version: "3.0"
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend/src:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app
